### ISSUE TITLE
failed to locate @require file ./normalize.css/normalize.css

### ISSUE THREAD

**Issue by fuzzthink** [docpress/docpress#102]
Do I need to do anything to use stylus?

No error if using css. Error if do.

docpress.json:
```
{
  "markdown": {
    "plugins": {
      "decorate": {}
    }
  },
  "css": [
    "docs/style.styl"
  ]
}
```

Error:
```
  ✗ /Users/john/dev/docsites/felix/node_modules/docpress/node_modules/docpress-base/data/style.styl:1:10
   1| @require './normalize.css/normalize.css'
---------------^
   2| @require './github-markdown-css/github-markdown.css'
   3| @require './nprogress/nprogress.css'
   4| @require './iconfonts/stylesheets/ionicons'

failed to locate @require file ./normalize.css/normalize.css
  
    1| @require './normalize.css/normalize.css'     
    ---------------^                                
    2| @require './github-markdown-css/github-markdown.css'  
    3| @require './nprogress/nprogress.css'         
    4| @require './iconfonts/stylesheets/ionicons'  
                                                    
    failed to locate @require file ./normalize.css/normalize.css  
                                                    
    at Evaluator.visitImport (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:901:21)  
    at Evaluator.Visitor.visit (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/visitor/index.js:28:40)  
    at Evaluator.visit (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:156:18)  
    at Evaluator.visitRoot (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:693:27)  
    at Evaluator.Visitor.visit (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/visitor/index.js:28:40)  
    at Evaluator.visit (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:156:18)  
    at Evaluator.evaluate (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:233:15)  
    at Renderer.render (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/stylus/lib/renderer.js:86:26)  
    at buildStylus (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/docpress-base/lib/build_css.js:37:7)  
    at buildCss (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/docpress-base/lib/build_css.js:8:3)  
    at Object.addCss (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/docpress-base/index.js:107:5)  
    at Ware.<anonymous> (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/wrap-fn/index.js:45:19)  
    at next (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/ware/lib/index.js:85:20)  
    at /Users/john/dev/docsites/felix/node_modules/docpress/node_modules/wrap-fn/index.js:121:18  
    at callback (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/docpress-base/index.js:120:5)  
    at useCache (/Users/john/dev/docsites/felix/node_modules/docpress/node_modules/docpress-base/lib/helpers/use_cache.js:6:5)  
```

**Comment by rstacruz** [comment]
Hmm, that should never show up. How did you install docpress and what
versions did you use?

**Comment by fuzzthink** [comment]
Tried all the following combinations:

global docpress only (both node 5.0 and 6.2)
global and local docpress (both node 5.0 and 6.2)
all 4 combinations has same error.

**Comment by knownasilya** [comment]
@fuzzthink why are you including the styles from docpress-base manually?

**Comment by fuzzthink** [comment]
@knownasilya I'm not including styles from docpress-base manually. I'm only defining styles in docs/style.styl.

**Comment by knownasilya** [comment]
Ok, I'll look into it.

**Comment by rstacruz** [comment]
I think I know what's causing this. Docpress-Base uses stylus only in
development. On the release version, it uses the pre-rendered style.css.
Stylus CSS apparently are only supported on development versions of
docpress-base.

**Comment by knownasilya** [comment]
Can we delete the CSS file and use the stylus only?

**Comment by rstacruz** [comment]
It would add something like 1 second to every build time, something that is
kinda painful in development. Maybe a Metalsmith stylus plugin would be
better suited.

**Comment by knownasilya** [comment]
Or the opposite, because everyone knows css but not stylus, so it'd be easier to contribute and less confusion if we have one base stylesheet.
