### ISSUE TITLE
Missing/misnamed stylesheets?

### ISSUE THREAD

**Issue by austinsc** [docpress/docpress#2]
Hi there, I'm excited for this project. I'm getting this error when I try to run docpress on a repo I'm working with (it has a readme and a docs/ folder).

```
  Docpress
  starting development - ^C to exit

   err ✗    first build
     ···    livereload
     ···    http://localhost:3000

            Starting up...

  ✗ /Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/docpress-base/data/style.styl:1:10
   1| @require './normalize.css/normalize.css'
    ✓ on    livereload
    ✓ on    http://localhost:3000                   n.css'
   3| @require './nprogress/nprogress.css'
            Running

failed to locate @require file ./normalize.css/normalize.css

    1| @require './normalize.css/normalize.css'
    ---------------^
    2| @require './github-markdown-css/github-markdown.css'
    3| @require './nprogress/nprogress.css'
    4| @require './iconfonts/stylesheets/ionicons'

    failed to locate @require file ./normalize.css/normalize.css

    at Evaluator.visitImport (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:901:21)
    at Evaluator.Visitor.visit (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitRoot (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:693:27)
    at Evaluator.Visitor.visit (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.evaluate (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/visitor/evaluator.js:233:15)
    at Renderer.render (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/stylus/lib/renderer.js:86:26)
    at buildStylus (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/docpress-base/lib/build_css.js:37:7)
    at buildCss (/Users/sca/.nvm/versions/node/v5.0.0/lib/node_modules/docpress/node_modules/docpress-base/lib/build_css.js:8:3)
```

To repro, you can clone https://github.com/RoviSys/signal-arr-proxygen and try running `docpress s` inside the dir.

```
npm i -g docpress
git clone https://github.com/RoviSys/signal-arr-proxygen
cd signal-arr-proxygen
docpress s
```

**Comment by rstacruz** [comment]
uh, hmm. interesting. lemme take a look at it on saturday

**Comment by rstacruz** [comment]
Okay, simple enough of a problem. Sorry for the oversight! v0.6.4 should fix this now.

**Comment by austinsc** [comment]
Awesome, that fixed it, thanks!

**Comment by rstacruz** [comment]
cool! let me know how the experience went for you. would love some feedback on docpress. http://ricostacruz.com has my email.
