### ISSUE TITLE
TypeError: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by MengFangui** [docpress/docpress#241]
C:\work\zweb-doc\node_modules\docpress-base\index.js:134
          if (!file.contents) return
                    ^

TypeError: Cannot read property 'contents' of undefined
    at scripts.map (C:\work\zweb-doc\node_modules\docpress-base\index.js:134:21)
    at Array.map (<anonymous>)
    at callback (C:\work\zweb-doc\node_modules\docpress-base\index.js:128:33)
    at C:\work\zweb-doc\node_modules\browserify\index.js:779:13
    at ConcatStream.<anonymous> (C:\work\zweb-doc\node_modules\concat-stream\index.js:36:43)
    at ConcatStream.emit (events.js:187:15)
    at finishMaybe (C:\work\zweb-doc\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:475:14)
    at endWritable (C:\work\zweb-doc\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at ConcatStream.Writable.end (C:\work\zweb-doc\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at Readable.onend (C:\work\zweb-doc\node_modules\readable-stream\lib\_stream_readable.js:577:10)

**Comment by MengFangui** [comment]
how to do? THANKS

**Comment by knownasilya** [comment]
What does your docpress config look like and what does your markdown look like?

**Comment by MengFangui** [comment]
https://github.com/limodou/vuecoms-doc  
you can test this docpress.


Docpress
  starting development - ^C to exit

    first build
aNA       livereload
aNA       http://localhost:3000
aNA
    Starting up...
aNA   aNA
  ✗ css: can't find 'lib/iview/styles/iview.css'
    at Object.addAsset (C:\work\vuecoms-doc-master\node_modules\docpress-base\index.js:91:11)
    at list.forEach (C:\work\vuecoms-doc-master\node_modules\docpress-base\index.js:60:7)
    at Array.forEach (<anonymous>)
    at Object.sortCss (C:\work\vuecoms-doc-master\node_modules\docpress-base\index.js:55:8)
    at Ware.<anonymous> (C:\work\vuecoms-doc-master\node_modules\wrap-fn\index.js:45:19)
    at next (C:\work\vuecoms-doc-master\node_modules\ware\lib\index.js:85:20)
    at C:\work\vuecoms-doc-master\node_modules\wrap-fn\index.js:121:18
    at Object.reset (C:\work\vuecoms-doc-master\node_modules\docpress-base\index.js:44:3)
    at Ware.<anonymous> (C:\work\vuecoms-doc-master\node_modules\wrap-fn\index.js:45:19)
    at next (C:\work\vuecoms-doc-master\node_modules\ware\lib\index.js:85:20)

aNA   aNA   aNA            Running                                 aNB



but it has 'lib/iview/styles/iview.css'.

My computer's operating system is win 10

**Comment by knownasilya** [comment]
Hum, works on macos. Will have to look deeper maybe with a VM..
